# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newapp
    pod 'Firebase/Core'

  target 'newappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'newappUITests' do
    # Pods for testing
  end

end
